# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyFAtJiil--BbUIOJwax8VA1p67zkqcc
"""

import streamlit as st
import pandas as pd
import os
from datetime import date

#App title
st.title("Pillars Bar Management App")

#Date and folder setup
today = st.date_input("Select Date", value=date.today())
folder = f"data/{today}"
os.makedirs(folder, exist_ok=True)

#Items list (add more as needed)
items = [
    "TUSKER", "PILISNER", "TUSKER MALT", "TUSKER LITE", "GUINESS KUBWA", "GUINESS SMALL",
    "SMIRNOFFICE", "SODA300ML", "VODKA 750ml", "GILBEYS 750m"
]

#Stock Sheet
st.header("Stock Sheet")
stock_df = pd.DataFrame({
    "Item": items,
    "Opening Stock": [0]*len(items),
    "Purchases": [0]*len(items),
    "Closing Stock": [0]*len(items),
    "Sales": [0]*len(items),
    "Price Per Item": [100]*len(items),
    "Amount": [0]*len(items)
})
stock_df = st.data_editor(stock_df, num_rows="dynamic", key="stock")

#Calculate
stock_df["Sales"] = stock_df["Opening Stock"] + stock_df["Purchases"] - stock_df["Closing Stock"]
stock_df["Amount"] = stock_df["Sales"] * stock_df["Price Per Item"]
stock_total = stock_df["Amount"].sum()

#Accommodation -
st.header("Accommodation Collection")
accom_df = pd.DataFrame({
    "1st Floor Rooms": [""],
    "Ground Floor Rooms": [""],
    "Money Lendered": [0],
    "Payment Method": [""]
})
accom_df = st.data_editor(accom_df, num_rows="dynamic", key="accom")
accom_total = accom_df["Money Lendered"].sum()

#Expenses
st.header("Expenses")
expenses_df = pd.DataFrame({
    "Description": [""],
    "Amount": [0]
})
expenses_df = st.data_editor(expenses_df, num_rows="dynamic", key="expenses")
expenses_total = expenses_df["Amount"].sum()

#Other Financials
st.header("Other Transactions")
money_to_boss = st.number_input("Money Paid to Boss", min_value=0)
money_from_chama = st.number_input("Money from Chama", min_value=0)

#Summary
st.header("Summary")
total_income = stock_total + accom_total + money_from_chama
profit = total_income - (expenses_total + money_to_boss)

st.metric("Total Sales", stock_total)
st.metric("Accommodation", accom_total)
st.metric("Expenses", expenses_total)
st.metric("Profit", profit)

#Save All
if st.button("Save All Data"):
    stock_df.to_csv(f"{folder}/stock.csv", index=False)
    accom_df.to_csv(f"{folder}/accommodation.csv", index=False)
    expenses_df.to_csv(f"{folder}/expenses.csv", index=False)
    summary_df = pd.DataFrame({
        "Metric": ["Sales", "Accommodation", "Chama", "Expenses", "Boss", "Profit"],
        "Amount": [stock_total, accom_total, money_from_chama, expenses_total, money_to_boss, profit]
    })
    summary_df.to_csv(f"{folder}/summary.csv", index=False)
    st.success("Data Saved Successfully")

pip install streamlit